# -*- coding: utf-8 -*-
"""Давиденко_DA6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kI1rSYLguk3O-PY-uygs-Cq3iLtPuQGl
"""

# Завантажимо Streamlit (не додавати в .py файл додатку)
!pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans

df = pd.read_csv('Smartphone_Usage_Productivity_Dataset_50000.csv')

df.info()

df.describe()

missing_data = df.isnull()
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

st.set_page_config(
    page_title="Smartphone Usage Dashboard",
    page_icon="📱",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.title("📱 Smartphone Usage & Productivity Dashboard")

st.markdown("""
Цей дашборд дозволяє аналізувати:
- використання смартфонів
- продуктивність
- сон та рівень стресу

📌 Використовуйте фільтри зліва
""")

st.sidebar.title("🔎 Панель фільтрації")

selected_gender = st.sidebar.selectbox(
    "Стать",
    df["Gender"].unique()
)

selected_occupation = st.sidebar.multiselect(
    "Професія",
    df["Occupation"].unique(),
    default=df["Occupation"].unique()
)

selected_device = st.sidebar.multiselect(
    "Тип пристрою",
    df["Device_Type"].unique(),
    default=df["Device_Type"].unique()
)

selected_stress = st.sidebar.radio(
    "Рівень стресу",
    df["Stress_Level"].unique()
)

selected_screen_time = st.sidebar.slider(
    "Максимальний час використання телефону",
    float(df["Daily_Phone_Hours"].min()),
    float(df["Daily_Phone_Hours"].max()),
    float(df["Daily_Phone_Hours"].max())
)

show_raw_data = st.sidebar.checkbox("📊 Показати сирі дані")

chart_option = st.sidebar.radio(
    "📈 Оберіть графік:",
    [
        "Screen Time vs Productivity",
        "Розподіл Screen Time",
        "Продуктивність по професіях",
        "Сон vs Стрес",
        "Кореляція",
        "Кластеризація користувачів"
    ]
)

st.sidebar.markdown("---")
st.sidebar.markdown("Фільтруйте дані та аналізуйте результати")

df_filtered = df[
    (df["Gender"] == selected_gender) &
    (df["Occupation"].isin(selected_occupation)) &
    (df["Device_Type"].isin(selected_device)) &
    (df["Stress_Level"] == selected_stress) &
    (df["Daily_Phone_Hours"] <= selected_screen_time)
]

st.subheader(f"🔍 Відфільтровано {df_filtered.shape[0]} записів")

csv = df_filtered.to_csv(index=False).encode("utf-8")

st.download_button(
    label="⬇️ Завантажити CSV",
    data=csv,
    file_name="filtered_data.csv",
    mime="text/csv"
)

st.subheader("📊 Таблиця даних")

all_columns = df_filtered.columns.tolist()

selected_columns = st.multiselect(
    "Оберіть стовпці",
    options=all_columns,
    default=all_columns[:6]
)

if selected_columns:
    st.dataframe(df_filtered[selected_columns])
else:
    st.info("Оберіть хоча б один стовпець")

if show_raw_data:
    st.subheader("📄 Повний датасет")
    st.dataframe(df)

if chart_option == "Screen Time vs Productivity":
    chart = alt.Chart(df_filtered).mark_circle(size=60).encode(
        x="Daily_Phone_Hours:Q",
        y="Work_Productivity_Score:Q",
        color="Gender:N"
    ).interactive()
    st.altair_chart(chart, use_container_width=True)

elif chart_option == "Розподіл Screen Time":
    fig, ax = plt.subplots()
    sns.histplot(df_filtered["Daily_Phone_Hours"], ax=ax)
    st.pyplot(fig)

elif chart_option == "Продуктивність по професіях":
    fig, ax = plt.subplots()
    sns.boxplot(data=df_filtered, x="Occupation", y="Work_Productivity_Score", ax=ax)
    plt.xticks(rotation=45)
    st.pyplot(fig)

elif chart_option == "Сон vs Стрес":
    chart = alt.Chart(df_filtered).mark_circle(size=60).encode(
        x="Sleep_Hours:Q",
        y="Stress_Level:Q"
    ).interactive()
    st.altair_chart(chart, use_container_width=True)

elif chart_option == "Кореляція":
    corr = df_filtered.select_dtypes(include=np.number).corr()
    fig, ax = plt.subplots()
    sns.heatmap(corr, annot=True, ax=ax)
    st.pyplot(fig)

elif chart_option == "Кластеризація користувачів":
    cluster_data = df_filtered[
        ["Daily_Phone_Hours", "Work_Productivity_Score"]
    ].dropna()

    if cluster_data.shape[0] >= 3:
        kmeans = KMeans(n_clusters=3)
        cluster_data["Cluster"] = kmeans.fit_predict(cluster_data)

        chart = alt.Chart(cluster_data).mark_circle(size=60).encode(
            x="Daily_Phone_Hours:Q",
            y="Work_Productivity_Score:Q",
            color="Cluster:N"
        ).interactive()

        st.altair_chart(chart, use_container_width=True)
    else:
        st.warning("Недостатньо даних")

st.sidebar.markdown("### 📉 Регресія")

numeric_columns = df_filtered.select_dtypes(include=np.number).columns.tolist()

if len(numeric_columns) >= 2:
    reg_x = st.sidebar.selectbox("X", numeric_columns)
    reg_y = st.sidebar.selectbox("Y", numeric_columns, index=1)
    show_regression = st.sidebar.checkbox("Показати регресію")
else:
    show_regression = False

if show_regression:
    df_reg = df_filtered[[reg_x, reg_y]].dropna()

    if df_reg.shape[0] >= 2:
        model = LinearRegression()
        model.fit(df_reg[[reg_x]], df_reg[reg_y])

        y_pred = model.predict(df_reg[[reg_x]])

        st.write("Коефіцієнт:", model.coef_[0])
        st.write("Intercept:", model.intercept_)
        st.write("R²:", model.score(df_reg[[reg_x]], df_reg[reg_y]))

        fig, ax = plt.subplots()
        sns.scatterplot(data=df_reg, x=reg_x, y=reg_y, ax=ax)
        sns.lineplot(x=df_reg[reg_x], y=y_pred, ax=ax)
        st.pyplot(fig)
    else:
        st.warning("Недостатньо даних")